# Generated by Django 2.2.3 on 2019-09-24 08:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamingnews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
    ]
