# Generated by Django 2.2.3 on 2019-09-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamingnews', '0004_auto_20190924_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='games/')),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
