# Generated by Django 2.2.3 on 2019-09-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamingnews', '0008_games_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='articles/'),
        ),
    ]
